### ISSUE TITLE
Fonts not appearing, has error in chrome tools

### ISSUE THREAD

**Issue by yndrelbosch** [bradleytaunt/ET-Jekyll#2]
When I try to load this on AWS with custom Site Title and all, I get this error on all the fonts: 

has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I honestly don't know how to fix this, or even what is really causing it.

**Comment by bradleytaunt** [comment]
The only two possibilities that come to my mind are:

1. Have you updated the `baseurl` in the `_config` file to your own current domain? If not, your server might be trying to call the `et-book` font from https://et-jekyll.netlify.com

or

2. Your AWS doesn't have the proper CORS authentication set. The best resource I've found on configuring CORS is: https://deliciousbrains.com/wp-offload-media/doc/configure-cors-to-resolve-web-font-issues/ (based on WordPress but still relevant for any server)

I hope one of these happens to be the issue 🤞

**Comment by bradleytaunt** [comment]
Closing this issue since it is based on server issues and not the Jekyll theme itself.
